package com.company.enums;

public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    SEND_PRODUCT_IMAGE,
    COMMIT_OR_ROLLBACK_ADD_PRODUCT, ENTERED_PRODUCT_DESCRIPTION, DELETED_PRODUCT, DELETE_PRODUCT;
}
